    --INSERT INTO tb_gestor VALUES (1);
    INSERT INTO TB_ETAPA VALUES (1, 'INSCRICAO');
    INSERT INTO TB_ETAPA VALUES (2, 'ENTREVISTA');
    INSERT INTO TB_ETAPA VALUES (3, 'ENTREVISTA TECNICA');
    INSERT INTO TB_ETAPA VALUES (4, 'SELECAO');
    INSERT INTO TB_ETAPA VALUES (5, 'PROPOSTA');

    INSERT INTO TB_PERFIL VALUES (1, 'GESTOR');
    INSERT INTO TB_PERFIL VALUES (2, 'RECRUTADOR');
    INSERT INTO TB_PERFIL VALUES (3, 'CANDIDATO');
