--INSERCAO DE PERFIL--
INSERT INTO TB_PERFIL VALUES (NEXT VALUE FOR perfil_sequence, 'GESTOR');
INSERT INTO TB_PERFIL VALUES (NEXT VALUE FOR perfil_sequence, 'RECRUTADOR');
INSERT INTO TB_PERFIL VALUES (NEXT VALUE FOR perfil_sequence, 'CANDIDATO');
INSERT INTO TB_PERFIL VALUES (NEXT VALUE FOR perfil_sequence, 'ADMINISTRADOR');

--INSERCAO DE USUARIOS--
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (98353850095, 'Steve Jobs', '11999999999', 'Masculino', 'Solteiro','09340340', '15', null, '1964-03-12', 1, 'Rogerio Jobs', 'Ana Luiz Jobs', 'steve.jobs@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME,  CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (49968313084, 'Bill Gates', '11555555555', 'Masculino', 'Casado','08340340', '130', 'apartamento 3', '1972-11-03', 1, 'Ronaldo Gates', 'Maria Faria Gates', 'bill.gates@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME,  CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (47881175095, 'Elon Musk', '11222222222', 'Masculino', 'Solteiro','03560780', '99', 'ap 7', '1988-12-09', 2, 'Cleber Silva Musk', 'Suzana Pereira Musk', 'elon.musk@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (12179330006, 'Jeff Bezos', '1133333333','Masculino', 'Solteiro','34560390', '1034', null, '1975-07-09', 2, 'Rodrigo Bezos', 'Aparecida Maria Bezos', 'jeff.bezos@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (83761594020, 'Mark Zuckerberg', '11545454545', 'Masculino', 'Solteiro','09340340', '1', null, '1964-03-12', 3, 'Claudio Zuckerberg', 'Maria Rosana Leite', 'mark.zuckerberg@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (48515000091, 'Susan Wojcick', null, 'Feminino', 'Casado','07620630', '999', null, '1984-12-01', 3, 'Marcos Carlos Wojcick', 'Bianca Wojcick', 'susan.wojcick@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (07867470050, 'Sherly Sandberg', '11666666666','Feminino', 'Solteiro','07340880', 'S/N', null, '1964-03-12', 3, null, 'Joana Sandberg', 'sherly.sandberg@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (05012529081, 'Tim Cook', '11777777777','Masculino', 'Solteiro','06500450', '17b', null, '1992-04-11', 3, 'Bruno Cook', 'Helena Maia Cook', 'tim.cook@foomail.com');
INSERT INTO TB_USUARIO (CPF, NOME, CELULAR, GENERO, ESTADO_CIVIL, CEP, NUMERO, COMPLEMENTO, DATA_NASCIMENTO, ID_PERFIL, NOME_PAI, NOME_MAE, NOME_USUARIO)
VALUES (63897500051, 'Larry Page', null, 'Masculino', 'Casado','09500700', '2345', 'ap 703', '1977-11-11', 4, 'Leandro Page', 'Alberta Page', 'larry.page@foomail.com');

--INSERCAO DE ETAPAS--
INSERT INTO TB_ETAPA VALUES (NEXT VALUE FOR etapa_sequence, 'INSCRICAO');
INSERT INTO TB_ETAPA VALUES (NEXT VALUE FOR etapa_sequence, 'ENTREVISTA');
INSERT INTO TB_ETAPA VALUES (NEXT VALUE FOR etapa_sequence, 'ENTREVISTA TECNICA');
INSERT INTO TB_ETAPA VALUES (NEXT VALUE FOR etapa_sequence, 'SELECAO');
INSERT INTO TB_ETAPA VALUES (NEXT VALUE FOR etapa_sequence, 'PROPOSTA');

--INSERCAO DE CARREIRAS--
INSERT INTO TB_CARREIRA VALUES (NEXT VALUE FOR carreira_sequence, 'DESENVOLVEDOR');
INSERT INTO TB_CARREIRA VALUES (NEXT VALUE FOR carreira_sequence, 'PRODUCT OWNER');
INSERT INTO TB_CARREIRA VALUES (NEXT VALUE FOR carreira_sequence, 'GERENTE');


--INSERCAO DE SOLICITACAO--

--INSERCAO DE VAGAS--

--INSERT DE ETAPA VAGA ORDEM--

--INSERT DE CANDIDATURA--

--INSERT DE FEEDBACK--


