--INSERCAO DE MEIOS DE PAGAMENTO--
--INSERT INTO TB_MEIO_PAGAMENTO (ID, DESCRICAO, SITUACAO) VALUES ('CREDITO','Cartão de Crédito', 'ATIVO');
--INSERT INTO TB_MEIO_PAGAMENTO (ID, DESCRICAO, SITUACAO) VALUES ('DEBITO','Cartão de Débito', 'ATIVO');
--INSERT INTO TB_MEIO_PAGAMENTO (ID, DESCRICAO, SITUACAO) VALUES ('PIX','Transferência PIX', 'ATIVO');

