--INSERCAO DAS NOTIFICACOES
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),3,'2023-02-01 18:45:00','TEMPO EXPIRADO', 'FINALIZADA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),2,'2023-09-01 08:11:00','FALTA DE CREDITO', 'ATIVA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),1,'2023-05-01 14:56:00','TEMPO EXPIRA EM 2 MIN', 'ATIVA');