--INSERCAO DAS NOTIFICACOES
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),3,'2024-02-01 18:45:00','TEMPO EXPIRADO', 'FINALIZADA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),2,'2024-09-01 08:11:00','FALTA DE CREDITO', 'ABERTA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),1,'2024-05-01 14:56:00','TEMPO EXPIRA EM 2 MIN', 'ENVIADA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),3,'2024-04-01 12:11:00','VEICULO REBOCADO', 'ABERTA');
INSERT INTO TB_NOTIFICACAO (ID, ID_VEICULO, DATA_HORA, CONTEUDO, SITUACAO) VALUES (NEXTVAL ('notificacao_sequence'),2,'2024-09-01 08:12:00','NOTIFICACAO FINALIZADA', 'FINALIZADA');